- hosts: all
  become: true
  tasks:
        - package: 
             name: "httpd"
             state: latest

        - copy: 
            src: "senthil.html"
            dest: "/var/www/html"

        - service:  
            name: "httpd" 
            state: started 
            enabled: true

