- hosts: all
  become: true
  vars: 
    - webPage: "senthil.html"
    - packageName: "httpd"
  tasks:
        - package: 
             name: "{{ packageName }}"
             state: latest

        - copy: 
            src: "{{ webPage }}"
            dest: "/var/www/html"

        - service:  
            name: "httpd" 
            state: started 
            enabled: true

