- hosts: all
  become: true
  vars: 
    - webPage: "senthil.html"
    - packageName: "httpd"
    - documentDir: "/var/www/senthil"
  tasks:
        - package: 
             name: "{{ packageName }}"
             state: latest

        - file: 
             state: directory
             path: "{{ documentDir }}"

        - copy:
             dest: "/etc/httpd/conf.d/senthil.conf"
             content: "DocumentRoot {{ documentDir }}\n"

        - copy: 
            src: "{{ webPage }}"
            dest: "{{ documentDir }}"

        - service:  
            name: "httpd" 
            state: started 
            enabled: true

